# .github/workflows/pages.yml
name: GitHub Pages (Next.js export)

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: portfolio/package-lock.json
      - name: Install deps
        run: npm ci
        working-directory: portfolio
      - name: Build (static export)
        run: npm run build
        working-directory: portfolio
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: portfolio/out

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4